package com.artifactId.random.texteditor;

import org.junit.Before;
import org.junit.Assert;
import org.junit.Test;

public class TextEditorTest {

  private TextEditor solution;

  @Before
  public void setUp() throws Exception {
    solution = new TextEditor();
  }

  @Test
  public void test1() {
    String[][] str = {
      {"APPEND", "Hey"},
      {"APPEND", " there"},
      {"APPEND", "!"}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{"Hey", "Hey there", "Hey there!"};

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test2() {
    String[][] str = {
      {"APPEND", "Hey you"},
      {"MOVE", "3"},
      {"APPEND", ","},
      {"MOVE", "0"},
      {"APPEND", "A"},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{"Hey you", "Hey you", "Hey, you", "Hey, you", "AHey, you"};

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test3() {
    String[][] str = {
      {"APPEND", "Hey you"},
      {"MOVE", "8"},
      {"APPEND", ","},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{"Hey you", "Hey you", "Hey you,"};

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test4() {
    String[][] str = {
      {"APPEND", "Hey you"},
      {"BACKSPACE"},
      {"MOVE", "0"},
      {"BACKSPACE"},
      {"MOVE", "2"},
      {"BACKSPACE"},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{"Hey you", "Hey yo", "Hey yo", "Hey yo", "Hey yo", "Hy yo"};

    Assert.assertEquals(expected, solution);
  }

  // LEVEL 2
  @Test
  public void test5() {
    String[][] str = {
      {"APPEND", "Hello cruel world!"},
      {"SELECT", "5", "11"},
      {"APPEND", ","},
      {"SELECT", "5", "12"},
      {"BACKSPACE"},
      {"SELECT", "4", "6"},
      {"MOVE", "1"},
      {"APPEND", ","},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{"Hello cruel world!", "Hello cruel world!", "Hello, world!",
      "Hello, world!", "Hello!", "Hello!", "Hello!", "H,ello!"};

    Assert.assertEquals(expected, solution);
  }


  @Test
  public void test6() {
    String[][] str = {
      {"APPEND", "Hello, world!"},
      {"SELECT", "5", "12"},
      {"COPY"},
      {"MOVE", "12"},
      {"PASTE"},
      {"PASTE"},
      {"SELECT", "5", "19"},
      {"PASTE"}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Hello, world!",
      "Hello, world!",
      "Hello, world!",
      "Hello, world!",
      "Hello, world, world!",
      "Hello, world, world, world!",
      "Hello, world, world, world!",
      "Hello, world, world!",
    };

    Assert.assertEquals(expected, solution);
  }


  // LEVEL 3
  @Test
  public void test7() {
    String[][] str = {
      {"APPEND", "Hello, world!"},
      {"SELECT", "7", "12"},
      {"BACKSPACE"},
      {"UNDO"},
      {"APPEND", "you"},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Hello, world!",
      "Hello, world!",
      "Hello, !",
      "Hello, world!",
      "Hello, you!"
    };

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test8() {
    String[][] str = {
      {"APPEND", "Hello, world!"},
      {"SELECT", "7", "12"},
      {"BACKSPACE"},
      {"MOVE", "6"},
      {"UNDO"},
      {"UNDO"},
      {"REDO"},
      {"REDO"},
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Hello, world!",
      "Hello, world!",
      "Hello, !",
      "Hello, !",
      "Hello, world!",
      "",
      "Hello, world!",
      "Hello, !"
    };

    Assert.assertEquals(expected, solution);
  }

  // -------------------------

  @Test
  public void test9() {
    String[][] str = {
      {"APPEND", "Hey, you!"},
      {"BACKSPACE"},
      {"APPEND", "? Impossibel!"},
      {"BACKSPACE"},
      {"BACKSPACE"},
      {"BACKSPACE"},
      {"APPEND", "le!"}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Hey, you!",
      "Hey, you",
      "Hey, you? Impossibel!",
      "Hey, you? Impossibel",
      "Hey, you? Impossibe",
      "Hey, you? Impossib",
      "Hey, you? Impossible!"
    };

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test10() {
    String[][] str = {{"APPEND", "Text generated by AI."}, // 0
      {"BACKSPACE"},
      {"APPEND", " that will conquer the world!"}, // 2
      {"APPEND", "!!"},
      {"UNDO"}, // 4
      {"APPEND", " Stop it!"}, //5
      {"UNDO"}, // 6
      {"REDO"}, // 7
      {"REDO"}, // 8
      {"UNDO"}, // 9
      {"UNDO"},
      {"UNDO"},
      {"REDO"},
      {"REDO"}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Text generated by AI.", //0
      "Text generated by AI",
      "Text generated by AI that will conquer the world!", //2
      "Text generated by AI that will conquer the world!!!",
      "Text generated by AI that will conquer the world!", // 4
      "Text generated by AI that will conquer the world! Stop it!", //5
      "Text generated by AI that will conquer the world!", // 6
      "Text generated by AI that will conquer the world! Stop it!", // 7
      "Text generated by AI that will conquer the world! Stop it!", // 8
      "Text generated by AI that will conquer the world!",
      "Text generated by AI",
      "Text generated by AI.",
      "Text generated by AI",
      "Text generated by AI that will conquer the world!"
    };

    Assert.assertEquals(expected, solution);
  }

  @Test
  public void test11() {
    String[][] str = {{"APPEND","Text generated by AI."}, //0
 {"BACKSPACE"},
 {"APPEND"," that will conquer the world!"}, //2
 {"APPEND","!!"},
 {"UNDO"}, //4
 {"APPEND","??????"},
 {"MOVE","19"}, //6
 {"SELECT","3","6"},
 {"MOVE","0"}, //8
 {"BACKSPACE"},
 {"MOVE","20"}, //10
 {"APPEND",""},
 {"UNDO"}, //12
 {"APPEND",""}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "Text generated by AI.",
      "Text generated by AI",
      "Text generated by AI that will conquer the world!",
      "Text generated by AI that will conquer the world!!!",
      "Text generated by AI that will conquer the world!",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!??????",
      "Text generated by AI that will conquer the world!",
      "Text generated by AI that will conquer the world!"
    };

    Assert.assertEquals(expected, solution);
  }

  // Level 4
  @Test
  public void test12() {
    String[][] str = {{"CREATE","file1"},
 {"CREATE","file2"},
 {"SWITCH","file1"},
 {"APPEND","Welcome to the content of file1!"},
 {"SWITCH","file2"},
 {"APPEND","File2 is also here."},
 {"SWITCH","file1"},
 {"BACKSPACE"},
 {"SWITCH","file2"},
 {"APPEND"," Welcome!"}
    };

    String[] solution = this.solution.solution(str);
    String[] expected = new String[]{
      "", "", "", "Welcome to the content of file1!", "", "File2 is also here.", "Welcome to the content of file1!", "Welcome to the content of file1", "File2 is also here.", "File2 is also here. Welcome!"
    };

    Assert.assertEquals(expected, solution);
  }



}